# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir I:/enel384/new384proj/new384proj.cache/wt [current_project]
set_property parent.project_path I:/enel384/new384proj/new384proj.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_cache_permissions disable [current_project]
read_vhdl -library xil_defaultlib I:/enel384/new384proj/new384proj.srcs/sources_1/new/traffic.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc I:/enel384/Vivado_Nexys4_Demo/Nexys4_Master.xdc
set_property used_in_implementation false [get_files I:/enel384/Vivado_Nexys4_Demo/Nexys4_Master.xdc]


synth_design -top traffic -part xc7a100tcsg324-1


write_checkpoint -force -noxdef traffic.dcp

catch { report_utilization -file traffic_utilization_synth.rpt -pb traffic_utilization_synth.pb }
