# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {H:/ENEL 384/Project/gran_velocidad_project/gran_velocidad/gran_velocidad.cache/wt} [current_project]
set_property parent.project_path {H:/ENEL 384/Project/gran_velocidad_project/gran_velocidad/gran_velocidad.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {h:/ENEL 384/Project/gran_velocidad_project/gran_velocidad/gran_velocidad.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {{H:/ENEL 384/Project/gran_velocidad_project/gran_velocidad/gran_velocidad.srcs/sources_1/new/gran_velocidad.vhd}}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{H:/ENEL 384/Project/gran_velocidad_project/gran_velocidad/Nexys4 DDR - Documentation and Files-20181114/Vivado_Nexys4DDR_Demo/Vivado_Nexys4DDR_Demo/Nexys4DDR_Master.xdc}}
set_property used_in_implementation false [get_files {{H:/ENEL 384/Project/gran_velocidad_project/gran_velocidad/Nexys4 DDR - Documentation and Files-20181114/Vivado_Nexys4DDR_Demo/Vivado_Nexys4DDR_Demo/Nexys4DDR_Master.xdc}}]


synth_design -top gran_velocidad -part xc7a100tcsg324-1


write_checkpoint -force -noxdef gran_velocidad.dcp

catch { report_utilization -file gran_velocidad_utilization_synth.rpt -pb gran_velocidad_utilization_synth.pb }
