# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a100tcsg324-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/duguidda/Desktop/Micro Electronics/Vivado_Nexys4DDR_Demo/Vivado_Nexys4DDR_Demo.cache/wt} [current_project]
set_property parent.project_path {C:/Users/duguidda/Desktop/Micro Electronics/Vivado_Nexys4DDR_Demo/Vivado_Nexys4DDR_Demo.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib {
  {C:/Users/duguidda/Desktop/Micro Electronics/Vivado_Nexys4DDR_Demo/Vivado_Nexys4DDR_Demo.srcs/sources_1/imports/Nexys4DDR_ISE_Basic/RGB_controller.vhd}
  {C:/Users/duguidda/Desktop/Micro Electronics/Vivado_Nexys4DDR_Demo/Vivado_Nexys4DDR_Demo.srcs/sources_1/imports/Nexys4DDR_ISE_Basic/UART_TX_CTRL.vhd}
  {C:/Users/duguidda/Desktop/Micro Electronics/Vivado_Nexys4DDR_Demo/Vivado_Nexys4DDR_Demo.srcs/sources_1/imports/Nexys4DDR_ISE_Basic/debouncer.vhd}
  {C:/Users/duguidda/Desktop/Micro Electronics/Vivado_Nexys4DDR_Demo/Vivado_Nexys4DDR_Demo.srcs/sources_1/imports/Nexys4DDR_ISE_Basic/GPIO_Demo.vhd}
}
read_xdc {{C:/Users/duguidda/Desktop/Micro Electronics/Vivado_Nexys4DDR_Demo/Vivado_Nexys4DDR_Demo.srcs/constrs_1/imports/final_projects/Nexys4DDR_Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/duguidda/Desktop/Micro Electronics/Vivado_Nexys4DDR_Demo/Vivado_Nexys4DDR_Demo.srcs/constrs_1/imports/final_projects/Nexys4DDR_Master.xdc}}]

catch { write_hwdef -file GPIO_demo.hwdef }
synth_design -top GPIO_demo -part xc7a100tcsg324-1
write_checkpoint GPIO_demo.dcp
catch { report_utilization -file GPIO_demo_utilization_synth.rpt -pb GPIO_demo_utilization_synth.pb }
